all: backend frontend

backend: backend.c
	gcc backend.c comm.c storage.c codecard.c receipt.c keyloader.c rsa.c -o backend

frontend: frontend.c
	gcc frontend.c comm.c codecard.c keyloader.c rsa.c -o frontend